"""The walkthrough pipeline's own contract, tested offline.

`tools/` is ~3,200 lines that record the agent and produce the published site,
and until now nothing tested any of it. That is not a tidiness complaint. The
pipeline has three properties that fail *silently*, and all three were found
while writing this module:

* **`tools/verify_gif.py` had never run.** Its node harness had
  ``const body = block.slice(body.indexOf('(function ()'));`` -- a binding named
  inside its own initializer, which is a `ReferenceError` under the temporal dead
  zone. So the tool whose entire job is to prove the inlined decoder reproduces
  Pillow aborted on line 7, before printing anything, and no eyeball would have
  caught it, because the failure lives in a subprocess whose stderr nobody reads.
  The decoder it was meant to check turns out to be correct -- all three checked-in
  recordings do match Pillow -- but that fact had never been established by
  anything. Hence `test_the_harness_never_names_a_binding_it_is_defining`, which
  needs no `node` and must never be skipped for want of one, and hence the round
  trip below, which does.

* **The generated artifacts have no generator-side check.** `docs/index.html` is
  generated (the player block is `tools/gif_player.js`, inlined by
  `tools/inject_player.py`) and `docs/favicon*.svg|png` are generated by
  `tools/make_favicon.py`. Both are checked in, neither was verified. A stale
  player means the published page runs a decoder that was never checked; a stale
  icon means the tab shows a colour the page stopped using. Both are re-derived
  here and compared -- in `tmp_path`, because this suite has no business rewriting
  the site as a side effect of asserting that it is up to date.

* **The player's URL is derived by string surgery.** `gif_player.js` recovers a
  recording from its poster with `src.replace("-still.png", ".gif")`, and the
  poster is what `write_gif` wrote with `path.replace(".gif", "-still.png")`.
  Nothing connects the two halves except the two literals, so a poster renamed in
  the page 404s the recording on a deployed site, with no build step in between to
  catch it. The rule is read out of the JavaScript rather than restated here, so
  changing it in one place and not the other fails.

Everything here is offline: frames are generated, fonts are found or skipped, and
`node` is used when present and skipped with a stated reason when not. Nothing
starts a browser, a container, or a turn.

Conventions: the modules under `tools/` are standalone scripts, not a package, so
they are loaded by path the way `test_adk_devui_patch.py` loads
`patch-adk-devui-mobile.py` -- no `sys.path` surgery, and no chance of the import
shadowing a real module name.

Two of the measurements below read the encoded bytes rather than asking Pillow to
decode them (`_gif_structure`, `_channel_error`). That is deliberate: Pillow's
decode API resolves colour tables and frame offsets before you can see them, and
the properties being asserted -- *one* palette for the whole file, *partial*
frames -- are properties of what the encoder wrote. Measuring them through the
decoder would mean measuring the decoder's opinion of them.
"""

from __future__ import annotations

import hashlib
import importlib.util
import inspect
import json
import os
import re
import shutil
import struct
import sys
from pathlib import Path

import pytest
from PIL import Image, ImageChops, ImageDraw

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOLS = REPO_ROOT / "tools"
DOCS = REPO_ROOT / "docs"
ASSETS = DOCS / "assets"
PAGE = DOCS / "index.html"

#: The four icons `docs/index.html` links, which is also everything
#: `tools/make_favicon.py` writes.
ICON_FILES = ("favicon.svg", "favicon-dark.svg", "favicon-32.png", "apple-touch-icon.png")

#: Every face `build_gifs.F()` can ask for, which is every combination of its two
#: flags. Listed in one place so the availability probe and the copy in the override
#: test cannot disagree about what "has the fonts" means.
FACES = ("DejaVuSans.ttf", "DejaVuSans-Bold.ttf", "DejaVuSansMono.ttf", "DejaVuSansMono-Bold.ttf")


def _load(name: str, filename: str):
    """Import a `tools/` script as a module, under a name that cannot collide."""
    spec = importlib.util.spec_from_file_location(name, TOOLS / filename)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


build_gifs = _load("tools_build_gifs", "build_gifs.py")
verify_gif = _load("tools_verify_gif", "verify_gif.py")
inject_player = _load("tools_inject_player", "inject_player.py")
make_favicon = _load("tools_make_favicon", "make_favicon.py")

NODE = shutil.which("node")
requires_node = pytest.mark.skipif(
    NODE is None,
    reason=(
        "node is not installed, and the decoder under test is JavaScript. Only the "
        "three cases that execute it are skipped; the Pillow-side and "
        "extraction-side checks around them still run, as does the case that "
        "asserts this path fails loudly rather than silently passing."
    ),
)


def _dejavu_dir() -> str | None:
    """A directory holding the DejaVu faces, or None.

    `build_gifs.F()` loads them by name from `font_dir()`. The cases that need a
    face skip rather than fail, because the whole point of the override is that
    this module has to work on a host without `fonts-dejavu-core` -- and skipping
    is how that gets demonstrated rather than assumed.
    """
    candidates = [
        build_gifs.font_dir(),
        *(
            "/usr/share/fonts/truetype/dejavu",
            "/usr/local/share/fonts/dejavu",
            "/Library/Fonts",
            "/System/Library/Fonts",
        ),
    ]
    for path in candidates:
        if all(os.path.exists(os.path.join(path, name)) for name in FACES):
            return path
    return None


DEJAVU = _dejavu_dir()
requires_dejavu = pytest.mark.skipif(
    DEJAVU is None,
    reason=(
        f"the DejaVu faces are not installed (looked in {build_gifs.font_dir()} and "
        "the usual system font directories). Install fonts-dejavu-core, or point "
        f"{build_gifs.FONTDIR_ENV} at a directory that has them; the rest of this "
        "module runs without them."
    ),
)


# --- frame generation ----------------------------------------------------------
#
# Drawn with plain Pillow and no TrueType face: most of this module must pass on a
# host with no font package at all, which is the portability the FONTDIR override
# exists to buy.


def _scene(index: int, total: int) -> Image.Image:
    """A frame with plenty of distinct colours and a visible label.

    The colour count is load-bearing rather than decorative: `write_gif` builds one
    shared palette out of at most 12 frames, so frames that each carry their own
    hundreds of colours are what make that palette observable in the output.
    """
    img = Image.new("RGB", (build_gifs.OUT_W, build_gifs.OUT_H), (10, 12, 16))
    d = ImageDraw.Draw(img)
    d.rectangle((0, 0, build_gifs.OUT_W, build_gifs.BAR), fill=(21, 26, 33))
    for k in range(40):
        d.rectangle(
            (6 + k * 22, 40 + (k % 8) * 60, 6 + k * 22 + 18, 90 + (k % 8) * 60),
            fill=(
                (index * 53 + k * 11) % 256,
                (index * 17 + k * 43) % 256,
                (index * 97 + k * 29) % 256,
            ),
        )
    d.rectangle((40, 540, 40 + 24 * (index + 1), 560), fill=(124, 178, 255))
    d.text((12, build_gifs.BAR // 2), f"scene {index + 1}/{total}", fill=(231, 236, 242))
    return img


def _capture(root: Path, frames: list[Image.Image], name: str = "live") -> build_gifs.Captures:
    """A `capture_ui.py` output directory, synthesised.

    `Captures` reads exactly two things -- `index.json` (`prompt`, plus `frames`
    with `file` and `t`) and the PNGs it points at -- so to every consumer in
    `build_gifs.py` this is a real capture, produced without a browser, a Marionette
    socket or a spent API key. The frames are `capture_ui.py`'s own size, 1400x900.
    """
    directory = root / name
    directory.mkdir(parents=True, exist_ok=True)
    index = {"prompt": "Summarize: something not in the vault yet", "frames": []}
    for i, img in enumerate(frames):
        filename = f"{name}-{i:03d}-frame.png"
        img.save(directory / filename)
        index["frames"].append({"file": filename, "t": round(i * 1.5, 2)})
    (directory / "index.json").write_text(json.dumps(index), encoding="utf-8")
    return build_gifs.Captures(str(root), name)


def _rgb_field(
    block=(255, 0, 0), size=(100, 100), at=(100, 100), background=(0, 0, 0)
) -> Image.Image:
    """A mostly-black 1400x900 frame with one solid block in it."""
    img = Image.new("RGB", (1400, 900), background)
    ImageDraw.Draw(img).rectangle((at[0], at[1], at[0] + size[0], at[1] + size[1]), fill=block)
    return img


# --- reading what the encoder wrote --------------------------------------------


def _gif_structure(path) -> dict:
    """The GIF's block structure: geometry, colour tables, frame rectangles.

    Pillow's decode API resolves all of this before a caller can see it -- a frame
    that is a sub-rectangle comes back as a full canvas, and a frame with its own
    colour table comes back with one shared palette attached. So the two properties
    this module wants to assert about `write_gif`'s output -- one palette for the
    file, frames that are only as large as what changed -- are properties of the
    *bytes*, and reading them back through a decoder would mean measuring the
    decoder's opinion instead.

    A GIF is: header, logical screen descriptor, optional global colour table,
    then a sequence of extension / image-descriptor / trailer blocks. Image
    descriptors carry their own optional colour table, then one LZW minimum-code-size
    byte, then the length-prefixed pixel sub-blocks. Anything this parser does not
    recognise ends the walk rather than raising, which is why the tests below also
    assert the frame count came out right.
    """
    raw = Path(path).read_bytes()
    if raw[:3] != b"GIF":
        raise AssertionError(f"{path} is not a GIF")
    width, height = struct.unpack_from("<HH", raw, 6)
    packed = raw[10]
    p = 13
    global_table = None
    if packed & 0x80:
        size = 1 << ((packed & 7) + 1)
        global_table = [tuple(raw[p + 3 * i : p + 3 * i + 3]) for i in range(size)]
        p += 3 * size

    frames = []
    while p < len(raw):
        block = raw[p]
        p += 1
        if block == 0x3B:  # trailer
            break
        if block == 0x21:  # extension
            p += 1  # the label
            if raw[p] == 0xF9:  # graphic control
                p += 1 + raw[p]  # size byte + fixed fields
            while raw[p]:  # sub-blocks
                p += 1 + raw[p]
            p += 1
            continue
        if block != 0x2C:  # not an image descriptor
            break
        left, top, w, h = struct.unpack_from("<HHHH", raw, p)
        p += 8
        ipacked = raw[p]
        p += 1
        local = None
        if ipacked & 0x80:
            size = 1 << ((ipacked & 7) + 1)
            local = [tuple(raw[p + 3 * i : p + 3 * i + 3]) for i in range(size)]
            p += 3 * size
        p += 1  # LZW minimum code size
        while raw[p]:
            p += 1 + raw[p]
        p += 1
        frames.append(
            {
                "left": left,
                "top": top,
                "width": w,
                "height": h,
                "palette": local or global_table,
                "has_local_palette": local is not None,
            }
        )
    return {"width": width, "height": height, "global_palette": global_table, "frames": frames}


def _channel_error(sources: list[Image.Image], gif_path) -> tuple[float, int, int]:
    """``(mean, 99.9th percentile, worst)`` absolute per-channel error.

    Vectorised through `ImageChops` and per-band histograms, because the obvious
    `zip(a, b)` over 1.76M bytes per frame is 42M Python iterations and turns a
    sub-second check into a fifteen-second one. The percentiles are reported rather
    than a bare maximum because a handful of antialiased glyph edges against a
    255-colour palette is expected and invisible, while a *shifted* palette moves
    the mean -- which is the failure that matters.
    """
    total = 0
    count = 0
    pooled = [0] * 256
    im = Image.open(gif_path)
    for i, source in enumerate(sources):
        im.seek(i)
        for band in ImageChops.difference(source, im.convert("RGB")).split():
            histogram = band.histogram()
            pooled = [a + b for a, b in zip(pooled, histogram, strict=True)]
            total += sum(level * n for level, n in enumerate(histogram))
            count += sum(histogram)
    everything = sum(pooled)
    seen = 0
    percentile = 0
    for level, n in enumerate(pooled):
        seen += n
        if seen >= 0.999 * everything:
            percentile = level
            break
    worst = max(level for level, n in enumerate(pooled) if n)
    return total / count, percentile, worst


# --- shared fixtures -----------------------------------------------------------


@pytest.fixture(scope="module")
def page_text() -> str:
    return PAGE.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def page_copy(tmp_path_factory, page_text) -> str:
    """The real page, copied into a temp directory.

    `verify_gif.py` and `inject_player.py` both take their input path from a module
    global, and both are run here against a copy: `main()` writes, and asserting
    that the published page is up to date is not a reason to overwrite it.
    """
    target = tmp_path_factory.mktemp("page") / "index.html"
    target.write_text(page_text, encoding="utf-8")
    return str(target)


@pytest.fixture(scope="module")
def film(tmp_path_factory) -> dict:
    """24 frames encoded by the real `write_gif`, and the report it returned.

    24 is the smallest count that makes `step = len(merged) // 12` exceed 1, so the
    montage becomes a *sampled* palette rather than an all-frames one. That is the
    normal case for a long recording, and the case where a colour that appears only
    in an unsampled frame still has to be approximated rather than lost.
    """
    frames = [(_scene(i, 24), 180) for i in range(24)]
    out = tmp_path_factory.mktemp("film") / "synthetic.gif"
    info = build_gifs.write_gif(frames, str(out), still=-1)
    return {
        "path": str(out),
        "frames": frames,
        "info": info,
        "still": out.with_name("synthetic-still.png"),
        "name": out.name,
    }


@pytest.fixture(scope="module")
def encoded(tmp_path_factory) -> dict:
    """Two small GIFs, written once by the real `write_gif`.

    One encode covers both halves of the consecutive-merge rule because the two
    properties are visible in the same output: `a a b c c` must collapse to three
    frames with summed durations, while the `a b a b` tail must not collapse at all.
    Splitting them would cost a second MEDIANCUT pass over a 2760x2560 montage, which
    is the same cost for three frames as for thirty and is what dominates this module.

    The file is named `e2e-some-recording.gif` rather than something convenient,
    because the naming rule the player depends on is the one under test.
    """
    root = tmp_path_factory.mktemp("encoded")
    a, b, c = _scene(0, 6), _scene(1, 6), _scene(2, 6)

    merged = root / "e2e-some-recording.gif"
    build_gifs.write_gif(
        [
            (a, 200),
            (a, 300),
            (b, 100),
            (c, 100),
            (c, 500),  # merges
            (a, 100),
            (b, 100),
            (a, 100),
            (b, 100),
        ],  # does not
        str(merged),
        still=0,
    )

    bare = root / "bare.gif"
    build_gifs.write_gif([(_scene(0, 1), 200)], str(bare))

    return {
        "root": root,
        "merged": merged,
        "bare": bare,
        "still": merged.with_name("e2e-some-recording-still.png"),
    }


# =============================================================================
# 1. write_gif: dedup, the shared montage palette, the still
# =============================================================================


def test_write_gif_reports_what_main_prints(film):
    """`main` formats `frames`, `ms` and `bytes` from this dict and nothing else.

    A renamed key is a `KeyError` at the end of a build that has already spent a
    real recording, so the contract is pinned where it is produced.
    """
    assert set(film["info"]) == {"frames", "ms", "bytes"}
    assert film["info"]["frames"] == len(film["frames"])
    assert film["info"]["ms"] == sum(ms for _, ms in film["frames"])
    assert film["info"]["bytes"] == os.path.getsize(film["path"])


def test_write_gif_merges_consecutive_identical_frames_and_adds_their_time(encoded):
    """The reason the merge exists: a pause must cost one frame of bytes.

    A recording holds on a scene while nothing moves, and `hold()` already collapses
    those into single frames -- but `films.py` stitches several scenes together, so an
    identical frame can also land at a scene boundary. Merging changes nothing a reader
    sees and can halve a file. The durations have to add, or the merge is not free: the
    scene would play faster than it was recorded.
    """
    structure = _gif_structure(encoded["merged"])
    assert len(structure["frames"]) == 7, (
        "the two extra a's and the two extra c's should have merged, and the a b a b "
        "tail should have survived: 9 frames in, 7 out"
    )

    durations = []
    im = Image.open(encoded["merged"])
    for i in range(im.n_frames):
        im.seek(i)
        durations.append(im.info.get("duration"))
    assert durations == [500, 100, 600, 100, 100, 100, 100], (
        "merged frames keep their total on-screen time"
    )


def test_write_gif_merges_only_consecutive_duplicates(encoded):
    """`a, b, a` stays three frames, and the file still says so in its pixels.

    The merge compares against the *last emitted* frame only, so a scene that returns
    to an earlier look does not collapse into it. A naive "drop any repeated frame"
    pass would get this wrong, and it is what keeps a loop that revisits a panel from
    losing the revisit. The last four frames of the same encode are `a b a b`, and
    frames 3 and 5 must be the *same picture* -- checked on the pixels rather than on
    a count, because a count alone cannot tell a preserved repeat from a reshuffle.
    """
    im = Image.open(encoded["merged"])
    pixels = []
    for i in range(im.n_frames):
        im.seek(i)
        pixels.append(im.convert("RGB").tobytes())
    assert len(pixels) == 7
    assert pixels[3] == pixels[5], "frames 3 and 5 are the same source frame"
    assert pixels[4] == pixels[6], "frames 4 and 6 are the same source frame"
    assert pixels[3] != pixels[4], "and they are not all the same picture"


def test_every_frame_is_quantized_against_one_shared_palette(film):
    """The montage's whole purpose: one palette for the file, not one per frame.

    Without it every frame would be quantized on its own, so the union of colours
    across the recording would grow with the frame count and two adjacent frames
    could disagree about a colour they share -- which is what a palette shift
    between two frames of the same panel looks like. Pillow writes each frame's
    palette into the frame itself, so the checkable form of "one palette" is that
    every colour table in the file is a subset of the single global one. A
    per-frame quantize breaks exactly that.
    """
    structure = _gif_structure(film["path"])
    assert structure["global_palette"], "the file has no global colour table at all"

    tables = [set(f["palette"]) for f in structure["frames"]]
    global_table = set(structure["global_palette"])
    stray = [i for i, table in enumerate(tables) if not table <= global_table]
    assert not stray, (
        f"frames {stray[:5]} carry colours that are not in the shared palette, so "
        "they were not quantized against the montage"
    )
    # Teeth: without this, a file whose frames happen to use four colours each would
    # pass the subset check whatever the encoder did.
    assert sum(len(t) for t in tables) > 255, (
        "the frames carry fewer colours in total than one palette holds, so the "
        "shared-palette property is not actually being tested"
    )
    # 255 entries rounded up to the next power of two on the way out; `quantize` is
    # what cannot ask for more than 255, and it is `write_gif` that asks.
    assert len(global_table) <= 256


def test_the_written_frames_still_look_like_the_frames_that_went_in(film):
    """A 255-colour palette is a lossy step, and the size of the loss is pinned.

    Quantizing is not free, so a regression that made the montage palette much worse
    would show up as poster-quality output rather than as a failing check -- which is
    why the bound is asserted rather than assumed. The mean is the meaningful number
    (measured here at 0.64 of a level per channel: invisible); the 99.9th percentile
    is the guard against a palette that is merely unlucky on one antialiased glyph
    edge. A *shifted* palette moves the mean, not the tail.
    """
    mean, percentile, worst = _channel_error([img for img, _ in film["frames"]], film["path"])
    assert mean < 4.0, f"mean channel error {mean:.2f} is visible banding"
    assert percentile <= 64, (
        f"the 99.9th percentile is {percentile} levels out of 255 (worst single pixel: {worst})"
    )


def test_the_still_is_the_frame_that_was_asked_for_at_full_size(film):
    """`still=-1` -- what every film in `films.py` asks for -- is the last frame.

    The poster is what a `prefers-reduced-motion` reader sees for good, so it has to
    be a frame of the recording rather than a thumbnail of one, and it has to be the
    frame the film named. It is written from the *quantized* image, so it is compared
    against Pillow's own decode of that frame: if the two ever diverged, the still
    would be showing colours the GIF itself cannot produce.
    """
    assert film["still"].is_file(), f"expected the still beside the gif: {film['still']}"
    still = Image.open(film["still"]).convert("RGB")
    assert still.size == (build_gifs.OUT_W, build_gifs.OUT_H), (
        "a half-size still is visibly soft at the width of the stage on a HiDPI "
        "screen -- the comment above write_gif's still branch says so"
    )

    im = Image.open(film["path"])
    im.seek(im.n_frames - 1)
    assert still.tobytes() == im.convert("RGB").tobytes()


def test_the_still_index_is_honoured_wherever_it_points(encoded):
    """`still=0` writes frame 0, not the last frame -- which is the whole point.

    Every film in `films.py` currently asks for `-1`, so an implementation that ignored
    the argument entirely would pass every one of them. The still is chosen by the
    film, and a film that chooses an earlier frame -- the prompt, before anything has
    happened -- is a reasonable thing to write, which is why the index is pinned
    against a file of seven frames and a request for the first.
    """
    im = Image.open(encoded["merged"])
    first = Image.open(encoded["still"]).convert("RGB").tobytes()

    im.seek(0)
    assert first == im.convert("RGB").tobytes()
    im.seek(2)
    assert first != im.convert("RGB").tobytes(), "it is not frame 2 either"
    im.seek(im.n_frames - 1)
    assert first != im.convert("RGB").tobytes(), "and it is not the last frame"


def test_no_still_is_written_unless_one_is_asked_for(encoded):
    """`build_films` may omit the key, and a stray -still.png would go stale.

    A poster left behind from an earlier build is worse than no poster: the page
    prefers it for a reduced-motion reader, so it would show a frame from a recording
    that no longer exists, and nothing in the build would notice.
    """
    assert encoded["bare"].is_file()
    assert not encoded["bare"].with_name("bare-still.png").exists()


# =============================================================================
# 2. Captures.distinct(): the near-identical frame drop
# =============================================================================


def test_distinct_drops_a_frame_that_moved_too_little_to_be_worth_playing(tmp_path):
    """The stated purpose: a progress bar ticking is not a scene change.

    Played at 190ms each, near-identical frames pad the loop and make a 40s turn feel
    longer than it was. A capture that is genuinely idle -- which `capture_ui.py`'s
    own `shoot()` avoids by comparing raw bytes, but which a stalled browser or a
    pending keyframe still produces -- has to collapse.
    """
    caps = _capture(
        tmp_path,
        [
            _rgb_field(size=(3, 3)),  # a dot, not a scene
            _rgb_field(size=(4, 4)),
            _rgb_field(size=(400, 300)),
        ],
    )  # a panel
    assert caps.distinct() == [0, 2], (
        "frame 1 changed a 3x3 dot, which is 9 pixels of 17760 after the thumbnail "
        "-- far under the 2% threshold, so it is padding"
    )


def test_distinct_keeps_a_frame_where_the_screen_actually_moved(tmp_path):
    """The other half: a generous threshold must not throw the content away."""
    frames = [_rgb_field(size=(200 + 200 * i, 300)) for i in range(4)]
    assert _capture(tmp_path, frames).distinct() == [0, 1, 2, 3]


def test_distinct_always_keeps_the_first_frame(tmp_path):
    """A recording that never changes still has to show something.

    `prev` is None on the first frame, so the threshold cannot be applied to anything
    and the frame is kept unconditionally. Without that, a static capture would encode
    to zero frames and `write_gif` would then fail on `quants[0]` -- an IndexError a
    long way from its cause.
    """
    assert _capture(tmp_path, [_rgb_field()]).distinct() == [0]


def test_a_capture_that_never_moves_collapses_to_one_frame(tmp_path):
    """The pathological recording, which is the case the method exists for."""
    caps = _capture(tmp_path, [_rgb_field() for _ in range(30)])
    assert len(caps) == 30
    assert caps.distinct() == [0]


def test_distinct_compares_against_the_last_kept_frame_not_the_previous_one(tmp_path):
    """`prev` only moves when a frame is kept, so a repeat of frame 0 is dropped.

    In `A, A', A` the near-duplicate is dropped *and* the exact repeat after it, because
    the thing being compared against is still A. The consequence is that a capture
    which oscillates does not collapse -- `A, B, A` keeps all three, since each A is
    compared against the B the reader last saw. That is the behaviour to know about
    before replacing it with a "have I seen this frame before?" set, which would
    freeze a legitimately repeating animation on its first pass.
    """
    a = _rgb_field(size=(400, 300))
    a_prime = _rgb_field(size=(400, 300), at=(101, 100))
    b = _rgb_field(size=(400, 300), at=(600, 400))
    assert _capture(tmp_path, [a, a_prime, a]).distinct() == [0]
    assert _capture(tmp_path, [a, b, a]).distinct() == [0, 1, 2]


def test_distinct_is_luminance_only_so_a_pure_hue_change_is_invisible(tmp_path):
    """The thumbnail is greyscale, so two very different frames can look equal.

    `(255,0,0)` and `(0,130,0)` both have luminance 76, so a frame that repaints a
    large area from one to the other produces an *identical* greyscale thumbnail and
    is dropped -- even though the RGB bytes differ across a third of the frame.
    Nothing in the walkthroughs changes only hue, so this is not a live bug; it is
    pinned because it is the assumption that would be quietly wrong if the comparison
    were ever ported to a perceptual metric, and because whoever does that port should
    find out here that the 2% threshold was chosen against greyscale.
    """
    red = _rgb_field(block=(255, 0, 0), size=(500, 500))
    green = _rgb_field(block=(0, 130, 0), size=(500, 500))
    assert red.convert("L").getpixel((300, 300)) == green.convert("L").getpixel((300, 300)) == 76
    assert red.tobytes() != green.tobytes(), "the frames must differ in RGB for this to bite at all"
    assert _capture(tmp_path, [red, green]).distinct() == [0]


def test_a_zero_threshold_keeps_every_frame(tmp_path):
    """`threshold=0.0` is the "do not drop anything" setting, and it has to mean it.

    The comparison is a strict `<`, so a threshold of zero can never be met and every
    frame is kept. Worth pinning because the alternative -- `<=` -- would still drop
    exact duplicates at 0.0, which is not what asking for no threshold is asking for.
    """
    caps = _capture(tmp_path, [_rgb_field() for _ in range(4)])
    assert caps.distinct(threshold=0.0) == [0, 1, 2, 3]


# =============================================================================
# 3. The extraction: lifting the decoder out of the page
# =============================================================================


def _player_page(body: str) -> str:
    """The smallest page that carries a player block, for the marker cases."""
    return (
        f"<html><body><script>\n{verify_gif.BEGIN}\n"
        f"{verify_gif.PLAYER_OPEN} {{\n{body}\n}})();\n"
        f"{verify_gif.END}\n</script></body></html>"
    )


def test_the_decoder_lifted_out_is_the_decoder_and_nothing_else(page_text):
    """The slice has to keep the LZW pass and drop the DOM half.

    Everything from `function lzwDecode` up to `/* --- player` is the pure decode;
    everything after it is transport that touches `document`, and evaluating that is
    what makes the harness possible at all. A slice running to the end of the IIFE
    would die on `document.fullscreenEnabled`, and a slice stopping early would
    silently decode nothing -- and neither `slice` call complains.
    """
    source = verify_gif.decoder_source(page_text)
    assert "function lzwDecode" in source
    assert "function decodeGif" in source
    assert "new Uint8Array" in source, "the LZW output buffer; proof the real pass is in there"
    assert "function GifPlayer" not in source, "the transport must not be evaluated"
    assert "document." not in source, (
        "the slice reached code that needs a DOM, so the harness would die on "
        "`document.fullscreenEnabled` instead of decoding anything"
    )
    assert source.strip().endswith("}"), "it must end on a complete function, not mid-body"


def test_a_missing_marker_is_reported_with_which_one_it_was():
    """`indexOf` returns -1 and `slice` treats it as "from the end of the string".

    So a renamed marker does not fail: it hands node some unrelated part of the page,
    and the TypeError that follows is several frames deep in a subprocess whose stderr
    nobody reads. That is exactly how the `const body = block.slice(body.indexOf(...))`
    defect stayed invisible. Every marker is checked and the message names the one that
    moved, so the fix is the next command rather than a bisect.
    """
    whole = _player_page(
        "function lzwDecode() { return new Uint8Array(0); }\n"
        "/* --- player --- */\nfunction GifPlayer() {}"
    )
    extracted = verify_gif.decoder_source(whole)
    assert extracted.startswith("function lzwDecode")
    assert "GifPlayer" not in extracted, "the slice must stop at the player marker"

    for marker, fragment in (
        (verify_gif.BEGIN, "the player block"),
        (verify_gif.END, "end marker"),
        (verify_gif.PLAYER_OPEN, "does not open"),
        (verify_gif.DECODER_START, "missing from the inlined player"),
        (verify_gif.DECODER_END, "missing from the inlined player"),
    ):
        damaged = whole.replace(marker, "/* something else */", 1)
        assert marker not in damaged, f"the marker {marker!r} was not the one removed"
        with pytest.raises(verify_gif.PlayerNotInlined) as excinfo:
            verify_gif.decoder_source(damaged)
        message = str(excinfo.value)
        assert fragment in message, f"the message for a missing {marker!r} should name it"
        assert "inject_player.py" in message, "the message must say what to run"


def test_the_python_and_javascript_extractions_slice_on_the_same_markers():
    """Two implementations of one rule, so they are asserted to agree.

    `decoder_source` is the Python copy of what the node harness does with four
    `indexOf` calls. They have to stay in step, or the tests below would be validating
    a slice the real verification never performs -- checking their own
    reimplementation. The harness is written with single quotes, so the literals are
    matched as substrings of it rather than by parsing JavaScript.
    """
    harness = verify_gif.HARNESS
    assert "'" + verify_gif.PLAYER_OPEN + "'" in harness
    assert "'" + verify_gif.DECODER_START + "'" in harness
    assert "'" + verify_gif.DECODER_END + "'" in harness
    assert "'/* === GIF PLAYER" in harness and "'/* === end GIF PLAYER" in harness


def test_the_harness_never_names_a_binding_it_is_defining():
    """The regression guard for the bug that made this whole module necessary.

    ``const body = block.slice(body.indexOf('(function ()'));`` is a temporal dead zone
    error: the initializer reads the binding it is defining, so node aborts before
    printing anything at all. The tool that exists to prove the decoder correct had
    therefore never proved anything, and nothing noticed, because the failure lives in
    a subprocess's stderr. There is no way to catch that by reading the Python, so the
    shape is caught as a shape -- which is why this case needs no `node` and must
    never be skipped for want of one.

    Comments are stripped first: the fix is documented beside the line it fixed, and a
    guard that reads its own regression note as a regression is worse than none.
    """
    pattern = re.compile(r"\b(?:const|let|var)\s+(\w+)\s*=[^;\n]*\b\1\s*[.\[(]")
    for line in verify_gif.HARNESS.splitlines():
        code = line.split("//", 1)[0]
        assert not pattern.search(code), (
            f"the harness reads a binding inside its own initializer: {line.strip()!r}. "
            "node raises a ReferenceError here and the run produces nothing at all."
        )


def test_pillow_hashes_are_one_hash_per_frame_and_are_stable(film):
    """The reference side, with nothing else involved.

    `verify_one` compares two lists and reports agreement, and a reference list that
    was empty -- or that moved between runs -- would make that comparison mean
    nothing. Pinned directly so a change to how the reference is derived cannot turn
    the round trip below into a tautology.
    """
    first = verify_gif.pillow_hashes(film["path"])
    assert len(first) == len(film["frames"]) == 24
    assert first == verify_gif.pillow_hashes(film["path"])
    assert all(len(h) == 16 for h in first)


def test_the_node_free_half_of_the_verifier_never_shells_out(film):
    """`pillow_hashes` and `decoder_source` work with no JavaScript runtime at all.

    This is the counterpart to the `node` skipif: it proves the checks that must
    survive a machine without node really do not reach for it, and -- by pointing
    `verify_one` at a runtime that is not there -- that the part which does reach for
    it fails *loudly*. A verification that reported success because it had decoded
    nothing would be the worst possible outcome for this file.
    """
    assert verify_gif.pillow_hashes(film["path"])
    with pytest.raises(RuntimeError) as excinfo:
        verify_gif.verify_one(film["path"], film["path"], node="/nonexistent/node")
    assert "not on PATH" in str(excinfo.value)


# =============================================================================
# 4. The round trip: the inlined decoder against Pillow
# =============================================================================


@requires_node
def test_the_inlined_decoder_reproduces_pillow_frame_for_frame(page_copy, film):
    """The property `tools/verify_gif.py` exists to establish, on a known input.

    Built here rather than read off `docs/assets/`, so the frames are known: every one
    of them is a known colour pattern, so a disagreement is a disagreement about the
    decoder and not about whatever happened to be in the recording. The page is the
    *real* page, copied, and the decoder comes out of it through the same slice the
    real tool uses.
    """
    report, problems = verify_gif.verify_one(page_copy, film["path"])
    assert problems == [], "\n".join(problems)
    assert report["frames"] == len(film["frames"])
    assert report["hashes"] == report["pillow"]
    assert (report["width"], report["height"]) == (build_gifs.OUT_W, build_gifs.OUT_H)


@requires_node
def test_the_frames_that_were_encoded_are_not_all_full_canvas(film):
    """Why the round trip above is a real test and not a formality.

    `write_gif` passes `optimize=True`, so Pillow writes each frame as the
    *sub-rectangle* that changed, with the rest of it absent. The harness has to honour
    those `left`/`top` offsets and compositing them correctly, and a decoder that
    ignored either would still give the right answer for a GIF written without
    optimization. If Pillow ever stops emitting partial frames this case fails and says
    why, which is the signal that the offsets are no longer covered.
    """
    structure = _gif_structure(film["path"])
    partial = [
        i
        for i, f in enumerate(structure["frames"])
        if (f["left"], f["top"]) != (0, 0)
        or (f["width"], f["height"]) != (structure["width"], structure["height"])
    ]
    assert partial, (
        "every frame is a full canvas, so the round trip is no longer exercising "
        "left/top offsets in the compositor"
    )
    assert any(f["has_local_palette"] for f in structure["frames"]), (
        "no frame carries its own colour table, so the palette branch of decodeGif is "
        "not covered either"
    )


@requires_node
def test_a_wrongly_decoding_page_is_reported_rather_than_passed(page_copy, film, tmp_path):
    """The negative control, without which the round trip proves nothing.

    Two lists of equal length agreeing is also what a decoder that returns zeros
    produces if the reference is wrong too, or if the harness silently emitted nothing.
    So the decoder is sabotaged -- `lzwDecode(...)` replaced by a buffer of zeroes,
    which composites the whole canvas to palette entry 0 -- and the comparison is
    required to notice.
    """
    page = Path(page_copy).read_text(encoding="utf-8")
    needle = "indices: lzwDecode(minCode, stream, w * h)"
    assert page.count(needle) == 1, (
        "the decoder's call site moved, so this case is no longer sabotaging it"
    )
    broken = tmp_path / "broken.html"
    broken.write_text(page.replace(needle, "indices: new Uint8Array(w * h)"), encoding="utf-8")

    report, problems = verify_gif.verify_one(str(broken), film["path"])
    assert problems, "a decoder that returns zeros was declared identical to Pillow"
    assert any("first difference at frame 0" in line for line in problems), problems
    assert report["frames"] == len(report["pillow"]), (
        "the frame count still matches, so this case is proving the hash comparison "
        "rather than the count"
    )


# =============================================================================
# 5. The generated artifacts are in sync with their generators
# =============================================================================


def test_injecting_the_player_leaves_the_checked_in_page_byte_identical(page_copy, monkeypatch):
    """`docs/index.html` is generated; this is the check that it was regenerated.

    The page carries a copy of `tools/gif_player.js` because it has to decode its own
    recordings with no build step and no network. Nothing connects the two, so a player
    edited and never re-inlined leaves the published site running the old decoder --
    and the decoder is precisely what `tools/verify_gif.py` proves against Pillow, so
    the proof would then be describing code that is not the code being served.

    Run against a copy, because `inject_player.main()` writes. The real file's digest
    is compared before and after to show it was not the thing that got rewritten.
    """
    before = hashlib.sha256(PAGE.read_bytes()).hexdigest()
    monkeypatch.setattr(inject_player, "PAGE", page_copy)
    assert inject_player.main() == 0
    assert Path(page_copy).read_bytes() == PAGE.read_bytes(), (
        "re-running tools/inject_player.py changes docs/index.html -- the player block "
        "in the page is not the current tools/gif_player.js. Re-run it and commit the "
        "result."
    )
    assert hashlib.sha256(PAGE.read_bytes()).hexdigest() == before, (
        "the real docs/index.html was modified by the test"
    )


def test_the_inlined_block_is_gif_player_js_verbatim(page_text):
    """The same fact, stated as what it is: one file, not a lookalike.

    Byte-identity of the whole page already covers this, but as a substring check it
    survives a *reformat* of the page around the block -- and it names both files,
    which is the actionable half of the failure message.
    """
    player = (TOOLS / "gif_player.js").read_text(encoding="utf-8").strip()
    start = page_text.index(verify_gif.BEGIN)
    end = page_text.index(verify_gif.END)
    assert page_text[start:end] == f"{verify_gif.BEGIN}\n{player}\n"


def test_injecting_twice_changes_nothing_and_leaves_one_block(tmp_path, monkeypatch):
    """Re-running the build must not append a second copy of 34KB of JavaScript.

    The second run takes the `if BEGIN in page` branch and rewrites the block in
    place. If that branch ever stopped matching, every `python3 tools/inject_player.py`
    would add another copy and the page would run the player N times -- N GifPlayers
    per figure, N fetch loops, N copies of every control. Nothing about that is an
    error.
    """
    fresh = tmp_path / "fresh.html"
    fresh.write_text("<html><body><p>page</p></body></html>", encoding="utf-8")
    monkeypatch.setattr(inject_player, "PAGE", str(fresh))

    assert inject_player.main() == 0
    once = fresh.read_text(encoding="utf-8")
    assert once.count(verify_gif.BEGIN) == 1
    assert once.index(verify_gif.BEGIN) < once.index("</body>"), (
        "the block belongs in the body, after the markup it decorates"
    )

    assert inject_player.main() == 0
    twice = fresh.read_text(encoding="utf-8")
    assert twice == once
    assert twice.count(verify_gif.BEGIN) == 1
    assert twice.count(verify_gif.END) == 1


def test_a_stale_inlined_block_is_replaced_rather_than_appended(page_copy, tmp_path, monkeypatch):
    """Editing the page inside the block by hand must not survive the next build.

    The branch keys on the *begin* marker, so a block whose body was corrupted -- an
    interrupted run, a merge that took the page side only -- is replaced whole. That
    the result is byte-identical to the checked-in page is the strongest statement
    available that the checked-in page is the generated one.
    """
    page = Path(page_copy).read_text(encoding="utf-8")
    start = page.index(verify_gif.BEGIN)
    end = page.index(verify_gif.END) + len(verify_gif.END)
    damaged = tmp_path / "damaged.html"
    damaged.write_text(
        page[:start] + verify_gif.BEGIN + "\nhalf a player\n" + verify_gif.END + page[end:],
        encoding="utf-8",
    )
    assert verify_gif.BEGIN in damaged.read_text(encoding="utf-8")
    monkeypatch.setattr(inject_player, "PAGE", str(damaged))

    assert inject_player.main() == 0
    assert damaged.read_text(encoding="utf-8") == page


def test_every_asset_the_page_references_exists(page_text):
    """A 404 on the published site is invisible until somebody opens the page.

    The page is deployed as a static artifact by a workflow that copies the folder, so
    nothing between editing it and shipping it checks that the file it points at is in
    the folder. The walkthrough posters and the four icon forms are the assets, and a
    walkthrough whose poster 404s renders as a broken image in place of the thing it is
    demonstrating.

    Anchors (`#/overview`, `#e2e-main`) and external URLs are skipped: they are not
    files in this folder.
    """
    referenced = set()
    for value in re.findall(r'(?:src|href)="([^"]+)"', page_text):
        if value.startswith(("#", "http://", "https://", "mailto:", "data:")):
            continue
        referenced.add(value.split("#", 1)[0])

    assert referenced, "no local asset references found -- this case is looking at nothing"
    missing = sorted(name for name in referenced if not (DOCS / name).exists())
    assert not missing, f"docs/index.html references files that are not in docs/: {missing}"

    stale = sorted(
        str(path.relative_to(DOCS))
        for pattern in ("e2e-*.gif", "e2e-*-still.png")
        for path in ASSETS.glob(pattern)
        if str(path.relative_to(DOCS)) not in referenced
    )
    assert not stale, (
        f"docs/assets holds recordings the page never shows: {stale}. They are "
        "published weight for nothing, and a film that is silently absent from the "
        "page is the one failure this section of the site cannot have."
    )


def test_the_page_declares_both_icon_variants_and_the_raster_fallbacks(page_text):
    """Four `<link>`s, and the missing ones are the ones nobody would notice.

    A deep-blue tab icon is invisible on a dark tab strip, which is why there are two
    SVGs, and iOS shows no icon at all unless the apple-touch link is there. None of
    that is a file-existence problem, so the case above cannot see it: dropping a
    `<link>` removes a reference and leaves the page perfectly valid.
    """
    for name in ICON_FILES:
        assert f'href="{name}"' in page_text, f"docs/index.html does not link {name}"
    assert 'media="(prefers-color-scheme: dark)"' in page_text, (
        "the dark icon has to be behind the media query or it wins everywhere"
    )
    assert page_text.count('rel="apple-touch-icon"') == 1


def test_the_icons_in_docs_are_the_ones_the_generator_produces(tmp_path, monkeypatch):
    """The page is the icon's source of truth; the checked-in files are a cache of it,
    and this is the check that the cache is warm.

    `make_favicon.py` reads `--primary` / `--on-primary` out of `docs/index.html`
    rather than repeating the hex, so a palette change cannot leave a stale hex lying
    around -- but it can leave stale *icons*, since nothing regenerates them.
    Regenerating into a temp directory and comparing catches both directions: a palette
    change that never regenerated the icons, and a hand-edited icon the next run would
    silently overwrite.

    It is also what covers the silent-breakage risk in the brief. `token_pair` raises
    `SystemExit` when it cannot find the tokens, which is loud -- but a *renamed*
    custom property that happened to match some other declaration, a
    `--primary-container:` say, would produce a plausible wrong colour instead. The
    comparison does not care how it went wrong.
    """
    monkeypatch.setattr(make_favicon, "DOCS", str(tmp_path))
    assert make_favicon.main() == 0
    for name in ICON_FILES:
        assert (DOCS / name).read_bytes() == (tmp_path / name).read_bytes(), (
            f"docs/{name} is not what tools/make_favicon.py produces now -- re-run it "
            "and commit the result"
        )


def test_the_icon_colours_come_from_the_light_and_dark_blocks_of_the_page(page_text):
    """The two variants must come from two *different* declarations.

    `token_pair` takes the last match in the slice it is given, and `main` splits the
    stylesheet at the dark-scheme media query -- so the light icon is drawn from the
    `:root` baseline and the dark one from the block that overrides it. If the split
    moved, or if both halves resolved to the same declaration, the generator would
    still succeed and both icons would come out the same colour, which is the one
    outcome the second variant exists to prevent.
    """
    css = page_text[page_text.index("<style>") :]
    dark_at = css.index("@media (prefers-color-scheme: dark)")
    light = make_favicon.token_pair(css[:dark_at])
    dark = make_favicon.token_pair(css[dark_at:])

    for name, pair in (("favicon.svg", light), ("favicon-dark.svg", dark)):
        svg = (DOCS / name).read_text(encoding="utf-8")
        assert f'fill="{pair[0]}"' in svg, f"docs/{name} is not drawn in {pair[0]}"
        assert f'fill="{pair[1]}"' in svg, f"docs/{name} glyph is not {pair[1]}"
    assert light[0] != dark[0] and light[1] != dark[1], (
        "the light and dark variants resolved to the same colours, so one of them is "
        "not being read from the block it is supposed to come from"
    )


# =============================================================================
# 6. The round trip between the writer's filename and the player's read of it
# =============================================================================


def test_the_player_derives_the_gif_from_the_poster_by_a_rule_it_does_not_share(page_text):
    """The rule is read out of the JavaScript rather than restated here.

    `GifPlayer` recovers a recording from its poster with
    `src.replace("-still.png", ".gif")`. Nothing in the build connects that to
    `write_gif`'s `path.replace(".gif", "-still.png")` except the two literals, so a
    poster renamed in the page fetches a URL that does not exist: the figure falls back
    to the native `<img>` and quietly loses every control, with no error anywhere.
    Parsing the rule out of the source means changing it in one place and not the
    other fails here.
    """
    player = (TOOLS / "gif_player.js").read_text(encoding="utf-8")
    rule = re.search(
        r'\(\s*this\.poster\.getAttribute\("src"\)\s*\|\|\s*""\s*\)\s*'
        r'\.replace\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)',
        player,
    )
    assert rule, "the poster src is no longer turned into a gif by a .replace()"
    needle, replacement = rule.group(1), rule.group(2)
    assert (needle, replacement) == ("-still.png", ".gif"), (
        f"the player now maps {needle!r} -> {replacement!r}; the build that writes "
        "those names and the page that refers to them need reconciling"
    )

    posters = re.findall(r'<img src="([^"]*-still\.png)"', page_text)
    assert posters, "no posters on the page, so the derived URL rule is not exercised"
    for poster in posters:
        derived = poster.replace(needle, replacement)
        assert (DOCS / derived).is_file(), (
            f"the player would fetch {derived} from the poster {poster}, and there is "
            "no such file: the figure would lose its transport and show the poster "
            "forever"
        )


def test_the_still_naming_rule_and_the_players_rule_are_inverses(encoded):
    """What the build writes is exactly what the player expects to read.

    `write_gif` derives the poster from the recording's own path, so the two halves
    only agree if the substitution round-trips for the names the build actually
    produces. The recordings are named after whatever film they are (`e2e-main.gif`,
    `e2e-gmail.gif`), so a rule that only works for one of them is enough to break the
    page -- which is why this is checked on a name the writer derived rather than on a
    hand-written one.
    """
    poster = encoded["still"].name
    assert poster == "e2e-some-recording-still.png"
    assert poster.replace("-still.png", ".gif") == "e2e-some-recording.gif"
    assert "e2e-some-recording.gif".replace(".gif", "-still.png") == poster
    assert encoded["still"].is_file(), (
        "the poster was not written where the player's rule says to look for it"
    )
    # And a sibling of the recording, not a file the page resolves some other way: the
    # src in the page is a plain relative path next to it.
    assert encoded["still"].parent == encoded["merged"].parent


# =============================================================================
# 7. FONTDIR: one host's font path, made overridable
# =============================================================================


def test_the_font_directory_defaults_to_the_constant(monkeypatch):
    """Nothing changes for existing use: unset, the path is the same as before.

    The expectation is a literal rather than `FONTDIR` itself, because a test that
    reads its expectation out of the thing under test asserts nothing.
    """
    monkeypatch.delenv(build_gifs.FONTDIR_ENV, raising=False)
    assert build_gifs.font_dir() == "/usr/share/fonts/truetype/dejavu"
    assert build_gifs.FONTDIR == "/usr/share/fonts/truetype/dejavu"


def test_the_font_directory_is_overridable(monkeypatch, tmp_path):
    """The reason the override exists: a hardcoded host path is a portability bug.

    `FONTDIR` names where `fonts-dejavu-core` installs on Debian and Ubuntu. On a host
    without that package -- a slim CI image, a macOS laptop, this very test suite's own
    portability claim -- every `Frame` construction raises from `ImageFont.truetype`,
    so no recording can be assembled at all. The environment variable turns the
    directory into a decision rather than a fact about the machine, and it is read per
    call so an override applied after import still takes effect.
    """
    monkeypatch.setenv(build_gifs.FONTDIR_ENV, str(tmp_path))
    assert build_gifs.font_dir() == str(tmp_path)


def test_a_missing_face_names_the_variable_that_overrides_it(monkeypatch, tmp_path):
    """`ImageFont.truetype`'s message names the file, not the way out of it.

    Left alone, a missing font package surfaces as "cannot find resource" from three
    frames deep inside a film, which reads as a broken recording rather than a missing
    dependency. The check is in the loader because that is the only place that can say
    which knob to turn.
    """
    monkeypatch.setenv(build_gifs.FONTDIR_ENV, str(tmp_path))
    build_gifs._fonts.clear()
    try:
        with pytest.raises(OSError) as excinfo:
            build_gifs.F(12)
    finally:
        build_gifs._fonts.clear()
    assert build_gifs.FONTDIR_ENV in str(excinfo.value)
    assert "fonts-dejavu-core" in str(excinfo.value)


@requires_dejavu
def test_f_loads_a_face_through_the_override(monkeypatch, tmp_path):
    """The override has to reach the font *loader*, not just be read back.

    The faces are copied rather than symlinked so the assertion is about which
    directory was opened, and the memo is cleared on both sides because `F` caches on
    `(size, bold, mono)` alone -- an override applied after a face was already loaded
    would otherwise be ignored, which is the one way this could pass vacuously.
    """
    for name in FACES:
        shutil.copy(os.path.join(DEJAVU, name), tmp_path / name)
    monkeypatch.setenv(build_gifs.FONTDIR_ENV, str(tmp_path))
    build_gifs._fonts.clear()
    try:
        face = build_gifs.F(13, bold=True, mono=True)
        assert str(tmp_path) in face.path
        assert face.size == 13
    finally:
        build_gifs._fonts.clear()


@requires_dejavu
def test_a_frame_is_the_size_the_page_lays_out_for():
    """`Frame` is 920x640 because the page's content column is 920 CSS px.

    The size is baked into the player: a frame of different dimensions is stretched by
    the page's own CSS and the type in a recording stops being the type the reader
    would see in the app. `shot` pastes a 908px chat column into an `OUT_W - 12` box, so
    a narrower `OUT_W` would clip it rather than scale it.
    """
    assert build_gifs.Frame("a title", build_gifs.BLUE, tag="t").done().size == (920, 640)
    assert build_gifs.OUT_W - 12 >= 908, "the chat column must fit without scaling"


@requires_dejavu
def test_screenshots_are_cropped_and_never_rescaled(tmp_path):
    """A recording's type has to be the type in the app, so nothing is scaled.

    `region` is documented as a 1:1 crop and `shot_fit` as the deliberate exception.
    The distinction is invisible in the output -- a scaled paste also looks like a
    paste -- so it is asserted on the pixels: `region` puts the source pixels at the
    destination unchanged, and `shot_fit` only ever makes them smaller.
    """
    shot = tmp_path / "shot.png"
    source = Image.new("RGB", (400, 300), (200, 100, 50))
    source.save(shot)

    frame = build_gifs.Frame("crop", build_gifs.BLUE)
    frame.region(str(shot), (0, 0, 40, 30), dst=(100, 200))
    assert frame.img.getpixel((110, 210)) == (200, 100, 50), (
        "region must paste the source pixels, not a resized version of them"
    )

    small = tmp_path / "small.png"
    Image.new("RGB", (40, 30), (200, 100, 50)).save(small)
    frame = build_gifs.Frame("fit", build_gifs.BLUE)
    frame.shot_fit(str(small), (0, 300, 300, 500))
    assert frame.img.getpixel((150, 400)) == (200, 100, 50), "nothing was pasted"
    assert frame.img.getpixel((2, 302)) == build_gifs.BG, (
        "shot_fit must never enlarge: a 40x30 screenshot in a 300x200 box stays 40x30, "
        "centred, and the box keeps its own background around it"
    )

    frame = build_gifs.Frame("fit", build_gifs.BLUE)
    frame.shot_fit(str(shot), (0, 300, 100, 500))
    assert frame.img.getpixel((50, 400)) == (200, 100, 50), (
        "a 400x300 screenshot must be scaled down to fit 100x200"
    )
    assert frame.img.getpixel((50, 320)) == build_gifs.BG, (
        "it fits the width and is centred vertically, so the top of the box is bare"
    )


# =============================================================================
# 8. Documentation drift, which is the one kind nothing else here can see
# =============================================================================


def test_no_tool_named_in_a_docstring_is_missing():
    """Every `tools/<file>` a reader is told to run has to exist.

    The mistake this pins was in the tree three times: the docstrings in
    `tools/gif_player.js`, `tools/inject_player.py` and `docs/index.html` all named
    `tools/verify_gif.js` for the check that lives in `tools/verify_gif.py` (whose own
    header named a third file, `verify_gif.js_check.py`). Fixed, but the shape of the
    mistake is worth guarding, because it is the one kind of drift no other case in
    this module can see: the decoder check, the favicon check and the player injection
    are all verified, and every docstring explaining how to run them pointed at
    nothing. A docstring is not code, so nothing reads it and nothing fails.

    `docs/index.html` is in the list because it carries a copy of the player's
    comments, so a docstring fix in `gif_player.js` that is not re-injected leaves the
    published page repeating the mistake -- which the byte-identity case above would
    catch for the block as a whole, but not for a reference to a third file.

    The pattern stops at a path segment rather than at the first `.`, because a
    trailing full stop ends the sentence and not the name: the first version of this
    read `tools/make_favicon.py.` and reported a file that does not exist.
    """
    sources = [TOOLS / "gif_player.js", TOOLS / "inject_player.py", TOOLS / "verify_gif.py", PAGE]
    reference = re.compile(r"tools/[\w-]+(?:\.[\w-]+)*")
    missing = []
    for source in sources:
        for name in sorted(set(reference.findall(source.read_text(encoding="utf-8")))):
            if not (REPO_ROOT / name).exists():
                missing.append(f"{source.relative_to(REPO_ROOT)} -> {name}")
    assert not missing, "docstrings name files that are not there: " + "; ".join(missing)


def test_the_guards_referenced_by_the_verifier_actually_exist():
    """`decoder_source`'s error message sends the reader to this file.

    Which means this file has to keep the case that justifies the message, or the
    advice points at a test that is no longer there. Cheap to check, and the failure
    it prevents is the worst kind: a diagnostic that names a path, run by someone
    three months from now, that resolves to nothing.
    """
    message_source = inspect.getsource(verify_gif.decoder_source)
    assert "tests/test_tools_gif.py" in message_source
    assert __file__.endswith("tests/test_tools_gif.py")
    assert "the markers are asserted" not in message_source, (
        "the message still points at an earlier wording of the case below"
    )
