#!/usr/bin/env python3
"""Inline the GIF player into docs/index.html.

Kept as a build step rather than hand-edited into the page because the decoder
below is a few hundred lines of code that has to stay byte-identical to the one
in tools/verify_gif.js, which is the copy proved frame-for-frame identical to
Pillow's decoder. Generate it, then check it in.

    python3 tools/inject_player.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = os.path.join(HERE, os.pardir, "docs", "index.html")
PLAYER = os.path.join(HERE, "gif_player.js")

BEGIN = "/* === GIF PLAYER (generated by tools/inject_player.py) === */"
END = "/* === end GIF PLAYER === */"


def main() -> int:
    with open(PAGE, encoding="utf-8") as fh:
        page = fh.read()
    with open(PLAYER, encoding="utf-8") as fh:
        player = fh.read().strip()

    if BEGIN in page:
        page = page[: page.index(BEGIN)] + BEGIN + "\n" + player + "\n" + END + "\n" + page[page.index(END) + len(END) + 1 :]
    else:
        anchor = "</body>"
        block = f"<script>\n{BEGIN}\n{player}\n{END}\n</script>\n"
        page = page.replace(anchor, block + anchor, 1)

    with open(PAGE, "w", encoding="utf-8") as fh:
        fh.write(page)
    size = len(re.search(re.escape(BEGIN) + ".*?" + re.escape(END), page, re.S).group(0))
    print(f"inlined {size:,} bytes of player into {os.path.relpath(PAGE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
