#!/usr/bin/env python3
"""Prove the GIF decoder inlined in docs/index.html matches Pillow, frame for frame.

The page decodes its own recordings so the transport controls can seek, pause
and slow them down -- CSS cannot do that to an animated image. A hand-written
LZW pass is exactly the kind of code that is subtly wrong in a way no eyeball
catches, so this compares its output against Pillow's decoder on every frame of
every recording and fails on a single differing byte.

    python3 tools/verify_gif.js_check.py      # or: node tools/verify_gif.js
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = os.path.join(HERE, os.pardir, "docs", "index.html")
ASSETS = os.path.join(HERE, os.pardir, "docs", "assets")

BEGIN = "/* === GIF PLAYER (generated by tools/inject_player.py) === */"
END = "/* === end GIF PLAYER === */"

HARNESS = r"""
// Pulls decodeGif out of the page and composes every frame the way a browser
// would, then prints one hash per frame for the Python side to compare.
const fs = require('fs'), crypto = require('crypto');
const page = fs.readFileSync(process.argv[2], 'utf8');
const block = page.slice(page.indexOf('/* === GIF PLAYER'), page.indexOf('/* === end GIF PLAYER'));
const body = block.slice(block.indexOf('(function ()'));
// Evaluate the IIFE with the DOM parts stubbed out, keeping the decoder.
const decoder = body.slice(body.indexOf('function lzwDecode'), body.indexOf('/* --- player'));
eval(decoder + '\nglobalThis.decodeGif = decodeGif;');

const file = process.argv[3];
const gif = decodeGif(new Uint8Array(fs.readFileSync(file)));

const W = gif.width, H = gif.height;
const canvas = new Uint8Array(W * H * 3);
let snapshot = null;
const hashes = [];
for (let i = 0; i < gif.frames.length; i++) {
  if (i > 0) {
    const prev = gif.frames[i - 1];
    if (prev.disposal === 2) {
      for (let y = prev.top; y < prev.top + prev.height; y++)
        for (let x = prev.left; x < prev.left + prev.width; x++) {
          const o = (x + y * W) * 3; canvas[o] = canvas[o + 1] = canvas[o + 2] = 0;
        }
    } else if (prev.disposal === 3 && snapshot) {
      canvas.set(snapshot);
    }
  }
  const f = gif.frames[i];
  if (f.disposal === 3) { snapshot = Uint8Array.from(canvas); }
  const pal = f.palette;
  for (let y = 0; y < f.height; y++) {
    for (let x = 0; x < f.width; x++) {
      const idx = f.indices[y * f.width + x];
      if (idx === f.transparent) continue;
      const px = f.left + x + (f.top + y) * W;
      if (px < 0 || px >= W * H) continue;
      canvas[px * 3] = pal[idx * 3];
      canvas[px * 3 + 1] = pal[idx * 3 + 1];
      canvas[px * 3 + 2] = pal[idx * 3 + 2];
    }
  }
  hashes.push(crypto.createHash('sha256').update(canvas).digest('hex').slice(0, 16));
}
console.log(JSON.stringify({ file: file.split('/').pop(), width: W, height: H,
                             frames: gif.frames.length, hashes }));
"""


def main() -> int:
    from PIL import Image

    with open(PAGE, encoding="utf-8") as fh:
        page = fh.read()
    if BEGIN not in page:
        print("FAIL: the player is not inlined in docs/index.html", file=sys.stderr)
        return 1

    gifs = sorted(f for f in os.listdir(ASSETS) if f.endswith(".gif"))
    if not gifs:
        print("FAIL: no recordings in docs/assets", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory() as tmp:
        harness = os.path.join(tmp, "harness.js")
        with open(harness, "w", encoding="utf-8") as fh:
            fh.write(HARNESS)
        failures = 0
        for name in gifs:
            path = os.path.join(ASSETS, name)
            out = subprocess.run(["node", harness, PAGE, path], capture_output=True, text=True)
            if out.returncode != 0:
                print(f"FAIL {name}: node exited {out.returncode}\n{out.stderr[-400:]}")
                failures += 1
                continue
            got = json.loads(out.stdout.strip().splitlines()[-1])

            im = Image.open(path)
            want = []
            for i in range(im.n_frames):
                im.seek(i)
                want.append(hashlib.sha256(im.convert("RGB").tobytes()).hexdigest()[:16])

            if got["frames"] != len(want) or got["hashes"] != want:
                failures += 1
                print(f"FAIL {name}: {len(want)} frames, decoder says {got['frames']}")
                for i, (a, b) in enumerate(zip(want, got["hashes"])):
                    if a != b:
                        print(f"     first difference at frame {i}: pillow {a} decoder {b}")
                        break
            else:
                print(f"ok   {name:18s} {got['width']}x{got['height']}  "
                      f"{got['frames']} frames identical to Pillow")
    if failures:
        print(f"\n{failures} recording(s) differ from Pillow's decode", file=sys.stderr)
        return 1
    print("\nThe inlined decoder reproduces Pillow byte for byte.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
