#!/usr/bin/env python3
"""Prove the GIF decoder inlined in docs/index.html matches Pillow, frame for frame.

The page decodes its own recordings so the transport controls can seek, pause
and slow them down -- CSS cannot do that to an animated image. A hand-written
LZW pass is exactly the kind of code that is subtly wrong in a way no eyeball
catches, so this compares its output against Pillow's decoder on every frame of
every recording and fails on a single differing byte.

    python3 tools/verify_gif.py

Nothing here needs a browser, a running stack or a live vault: it reads the
checked-in page and the checked-in recordings. The parts are exposed as callables
(``decoder_source``, ``pillow_hashes``, ``verify_one``) rather than left inside
``main`` because the slice that lifts the decoder out of the page is itself the
part that can rot -- it is four ``indexOf`` calls against marker strings, and
nothing but this file knows they still match. ``tests/test_tools_gif.py`` drives
those callables on a synthetic GIF built in a temp directory, so the contract is
covered even on a machine with no ``node`` and no recordings.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = os.path.join(HERE, os.pardir, "docs", "index.html")
ASSETS = os.path.join(HERE, os.pardir, "docs", "assets")

BEGIN = "/* === GIF PLAYER (generated by tools/inject_player.py) === */"
END = "/* === end GIF PLAYER === */"

# The same four literals the node harness in HARNESS below slices on, spelled out
# here so the extraction is testable in Python and the two cannot drift apart
# without one of the two tests noticing.
PLAYER_OPEN = "(function ()"
DECODER_START = "function lzwDecode"
DECODER_END = "/* --- player"

HARNESS = r"""
// Pulls decodeGif out of the page and composes every frame the way a browser
// would, then prints one hash per frame for the Python side to compare.
const fs = require('fs'), crypto = require('crypto');
const page = fs.readFileSync(process.argv[2], 'utf8');
const block = page.slice(page.indexOf('/* === GIF PLAYER'), page.indexOf('/* === end GIF PLAYER'));
// `block`, not `body`: `const body = block.slice(body.indexOf(...))` names the
// binding being initialised, which is a ReferenceError under the temporal dead
// zone, so this line aborted before it printed anything. Nothing ran it, so
// nothing caught it -- see tests/test_tools_gif.py, which now runs the harness.
const body = block.slice(block.indexOf('(function ()'));
// Evaluate the IIFE with the DOM parts stubbed out, keeping the decoder.
const decoder = body.slice(body.indexOf('function lzwDecode'), body.indexOf('/* --- player'));
eval(decoder + '\nglobalThis.decodeGif = decodeGif;');

const file = process.argv[3];
const gif = decodeGif(new Uint8Array(fs.readFileSync(file)));

const W = gif.width, H = gif.height;
const canvas = new Uint8Array(W * H * 3);
let snapshot = null;
const hashes = [];
for (let i = 0; i < gif.frames.length; i++) {
  if (i > 0) {
    const prev = gif.frames[i - 1];
    if (prev.disposal === 2) {
      for (let y = prev.top; y < prev.top + prev.height; y++)
        for (let x = prev.left; x < prev.left + prev.width; x++) {
          const o = (x + y * W) * 3; canvas[o] = canvas[o + 1] = canvas[o + 2] = 0;
        }
    } else if (prev.disposal === 3 && snapshot) {
      canvas.set(snapshot);
    }
  }
  const f = gif.frames[i];
  if (f.disposal === 3) { snapshot = Uint8Array.from(canvas); }
  const pal = f.palette;
  for (let y = 0; y < f.height; y++) {
    for (let x = 0; x < f.width; x++) {
      const idx = f.indices[y * f.width + x];
      if (idx === f.transparent) continue;
      const px = f.left + x + (f.top + y) * W;
      if (px < 0 || px >= W * H) continue;
      canvas[px * 3] = pal[idx * 3];
      canvas[px * 3 + 1] = pal[idx * 3 + 1];
      canvas[px * 3 + 2] = pal[idx * 3 + 2];
    }
  }
  hashes.push(crypto.createHash('sha256').update(canvas).digest('hex').slice(0, 16));
}
console.log(JSON.stringify({ file: file.split('/').pop(), width: W, height: H,
                             frames: gif.frames.length, hashes }));
"""


class PlayerNotInlined(RuntimeError):
    """The page does not carry the block the decoder is sliced out of."""


def decoder_source(page: str) -> str:
    """The decoder, lifted out of `page` exactly the way the node harness does.

    Four ``indexOf`` calls against marker strings, and the whole proof rests on
    them: an ``indexOf`` that misses returns -1, and ``slice`` silently turns
    that into a substring from the end of the string rather than an error. So a
    renamed marker does not fail loudly here, it hands node some other part of the
    page -- and the resulting TypeError is a few frames deep in someone else's
    stack. Every miss is therefore checked.

    :raises PlayerNotInlined: with the marker that was not found.
    """
    for marker, what in ((BEGIN, "the player block"), (END, "its end marker")):
        if marker not in page:
            raise PlayerNotInlined(
                f"{what} ({marker!r}) is not in the page. Run "
                "python3 tools/inject_player.py -- if that still does not find it, "
                "the page and the script have drifted apart and one of them is stale."
            )
    block = page[page.index(BEGIN): page.index(END)]
    if PLAYER_OPEN not in block:
        raise PlayerNotInlined(
            f"{PLAYER_OPEN!r} does not open the inlined player. Run "
            "python3 tools/inject_player.py -- if that still does not put it back, the "
            "page and the script have drifted apart and one of them is stale.")
    body = block[block.index(PLAYER_OPEN):]
    for marker in (DECODER_START, DECODER_END):
        if marker not in body:
            raise PlayerNotInlined(
                f"{marker!r} is missing from the inlined player, so there is no "
                "decoder to lift out of it. The marker lives in tools/gif_player.js, "
                "so run python3 tools/inject_player.py -- and if it is still missing "
                "after that, the player was restructured and the marker has to move, "
                "in this file and in tests/test_tools_gif.py together."
            )
    return body[body.index(DECODER_START): body.index(DECODER_END)]


def _hash(pixels: bytes) -> str:
    return hashlib.sha256(pixels).hexdigest()[:16]


def pillow_hashes(gif_path: str) -> list[str]:
    """One hash per frame from Pillow's own decoder, composited by Pillow.

    ``Image.seek`` walks the file's own frame graph, so this is the reference
    answer, not a reimplementation of one: whatever the browser would show
    natively is what ``convert("RGB")`` gives here.
    """
    from PIL import Image

    im = Image.open(gif_path)
    want = []
    for i in range(im.n_frames):
        im.seek(i)
        want.append(_hash(im.convert("RGB").tobytes()))
    return want


def decode_hashes(page_path: str, gif_path: str, *, node: str = "node") -> dict:
    """Run the node harness and return its parsed report.

    The harness is written to a temp directory rather than next to the page so
    this is callable from a test without leaving anything behind.

    :raises RuntimeError: node is missing or exited non-zero.
    """
    with tempfile.TemporaryDirectory() as tmp:
        harness = os.path.join(tmp, "harness.js")
        with open(harness, "w", encoding="utf-8") as fh:
            fh.write(HARNESS)
        try:
            out = subprocess.run([node, harness, page_path, gif_path],
                                 capture_output=True, text=True, timeout=300)
        except FileNotFoundError:
            raise RuntimeError(
                f"{node!r} is not on PATH. The decoder is JavaScript, so proving it "
                "against Pillow needs a JS runtime; install node, or accept that "
                "this check has not run."
            ) from None
    if out.returncode != 0:
        raise RuntimeError(f"node exited {out.returncode}\n{out.stderr[-400:]}")
    lines = out.stdout.strip().splitlines()
    if not lines:
        raise RuntimeError("node printed nothing -- the harness did not reach its report")
    return json.loads(lines[-1])


def verify_one(page_path: str, gif_path: str, *, node: str = "node") -> tuple[dict, list[str]]:
    """Compare one recording, the way `main` does. Returns ``(report, failures)``.

    ``report`` is the harness's own output (frame count, size, per-frame hashes)
    with Pillow's hashes added under ``"pillow"``, so a caller that wants to
    assert on the numbers can. ``failures`` is empty when the two agree on every
    frame; each entry is one line of the report ``main`` prints.
    """
    got = decode_hashes(page_path, gif_path, node=node)
    want = pillow_hashes(gif_path)
    got["pillow"] = want
    failures = []
    if got["frames"] != len(want) or got["hashes"] != want:
        failures.append(
            f"FAIL {os.path.basename(gif_path)}: {len(want)} frames, "
            f"decoder says {got['frames']}")
        for i, (a, b) in enumerate(zip(want, got["hashes"])):
            if a != b:
                failures.append(
                    f"     first difference at frame {i}: pillow {a} decoder {b}")
                break
    return got, failures


def main() -> int:
    with open(PAGE, encoding="utf-8") as fh:
        page = fh.read()
    if BEGIN not in page:
        print("FAIL: the player is not inlined in docs/index.html", file=sys.stderr)
        return 1

    gifs = sorted(f for f in os.listdir(ASSETS) if f.endswith(".gif"))
    if not gifs:
        print("FAIL: no recordings in docs/assets", file=sys.stderr)
        return 1

    bad = 0
    for name in gifs:
        path = os.path.join(ASSETS, name)
        try:
            got, problems = verify_one(PAGE, path)
        except RuntimeError as exc:
            print(f"FAIL {name}: {exc}")
            bad += 1
            continue
        # Counted per recording, not per printed line: a frame-count mismatch
        # prints two lines and is still one recording that differs.
        bad += bool(problems)
        for line in problems:
            print(line)
        if not problems:
            print(f"ok   {name:18s} {got['width']}x{got['height']}  "
                  f"{got['frames']} frames identical to Pillow")
    if bad:
        print(f"\n{bad} recording(s) differ from Pillow's decode", file=sys.stderr)
        return 1
    print("\nThe inlined decoder reproduces Pillow byte for byte.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
